name: Stable Compilation

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  docker:
    name: ${{ matrix.image }}
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}

    strategy:
      fail-fast: false
      matrix:
        image:
          - ubuntu:20.04  # CMake 3.16.3 - g++ 9.3.0  - LTS
          - debian:11     # CMake 3.18.4 - g++ 10.2.1 - oldstable
          - ubuntu:22.04  # CMake 3.22.1 - g++ 11.2.0 - LTS
          - debian:12     # CMake 3.25.1 - g++ 12.2.0 - stable

    steps:
      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND="noninteractive"
          apt-get update
          apt-get install -y --no-install-recommends --no-install-suggests \
            build-essential cmake ninja-build git \
            libicu-dev libexpat1-dev

      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Compile
        run: |
          cmake -G Ninja -B build . \
            -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr
          cmake --build build

      - name: Install
        run: |
          cmake --install build

      - name: Test
        run: cmake --build build --target check
